# Generated by Django 3.2.16 on 2022-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2022-12-28 17:11')),
                ('filePath', models.CharField(default='', max_length=200)),
                ('fileName', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
